### ISSUE TITLE
Write GPMF data to an MP4 file

### ISSUE THREAD

**Issue by ncoder-1** [gopro/gpmf-write#1]
Would it be possible to provide demo code of actually writing GPMF data to an MP4 file in a new or existing "GoPro MET" track?  Or at the very least write the GPMF data to a binary file that can then be multiplexed after-the-fact into an MP4 using `ffmpeg`?

It is not very clear what `GPMF_demo.c` is actually doing since it's not writing either to an MP4 file or even a simple file, from what I can gather it is writing in-memory to a buffer.

**Comment by dnewman-gpsw** [comment]
I agree.  The issue is adding a small MP4 writer, just as I did for the reader.  I don't want to burden this repo with one of the very heavy tools that support MP4 exports. I know a lightweight MP4 muxer can be done, I just need to find the time, or someone to a compatible open source project that is lightweight enough.

**Comment by dnewman-gpsw** [comment]
demo.c is formatting a GPMF payload that would be written into a MP4 track.  GPMFWriteGetPayload(gpmfhandle, GPMF_CHANNEL_TIMED, (uint32_t *)buffer, sizeof(buffer), &payload, &payload_size); 

payload and its size, is what needs to be muxed into an MP4.

**Comment by dnewman-gpsw** [comment]
I'll leave this open and a reminder.

**Comment by dnewman-gpsw** [comment]
I have a demo of this working in the develop branch.  
gpmf-writer <new_Filename.mp4> <file_time_base> <gpmf_payload_duration_timebase>
gpmf-writer newgpmf.mov 1000 1001

You can then use ffmpeg to mux this into a file with video and audio.
ffmpeg -i GF020101.MP4 -i newgpmf.mov -map 0:0:0 -map 0:1:1 -map 1:0:2 -c copy GF020101NEW.MP4

**Comment by ncoder-1** [comment]
Awesome!  I'll have a look at it this week.  Thanks for making this!

**Comment by erlenner** [comment]
Just wanted to let you guys know that I've made my own gstreamer implementation of this project. The [demo](https://github.com/BluEye-Robotics/mp4-inject-sensor-data) is a work in progress in the sense that it uses a [custom version of the mp4mux gstreamer element](https://gitlab.freedesktop.org/erlend_ne/gst-plugins-good/tree/mp4mux-add-gpmf-track), and the modifications won't get picked up by gstreamer before there is more downstream support for gpmf. It works though.

**Comment by erlenner** [comment]
Nice project, by the way.

**Comment by erlenner** [comment]
The gstreamer pull request is [here](https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/merge_requests/91)

**Comment by dnewman-gpsw** [comment]
Very nice.  GoPro has used GStreamer in the past, but never had GPMF writing abilities -- this is very good to know.
