### ISSUE TITLE
[Question] Matroska container support

### ISSUE THREAD

**Issue by mndar** [gopro/gpmf-write#14]
Will it be possible to use gpmf-write and Go Pro Metadata structure with the Matroska container?

What kind of changes I am looking at if I have to make it work?

**Comment by dnewman-gpsw** [comment]
GPMF is pretty much container independent, although I'm not familiar with particulars of the Matroska file structure.

**Comment by mndar** [comment]
Thanks. I am trying to understand if it's possible to use a muxer in GStreamer with GPMF.
 
From GPMF Readme, I understood that
GPMF is a stored as a track in the container and is similar to PCM audio.

So is my understanding correct when I say that a MP4 file with GPMF metadata has an extra track dedicated to metadata?

**Comment by dnewman-gpsw** [comment]
Yes.  GPMF uses the track timing to describe the relationship between the streams (metadata to video timing.)

**Comment by mndar** [comment]
Thanks. That's what I was looking for.
